### ISSUE TITLE
Implementere funksjonalitet for å hente inn expo-token og sende ut push notifications

### ISSUE THREAD

**Issue by sveggen** [difi/dc20-digitalborger-frontend#123]
## Front End:
- [ ] Lage funksjon som sender inn token til server når bruker logger inn
- [ ] Lage funksjon som oppdaterer badge count og sender denne inn til server når bruker går inn på "Varsel"- fanen aka. har sett varselen

## Back End
- [x] Lage Controller som henter inn tokens, og legger disse til som nodes
- [x] Lage funksjon i Controller som henter inn badgecount
- [x] Oppdatere hook for å loope igjennom alle nodes og hente ut tokens og badgecount

**Comment by hegeaal** [comment]
Er det greit om tokenet blir sendt hver gang isteden for kun første gang brukerene logger inn?

**Comment by sveggen** [comment]
@hegeaal ja det er greit
