### ISSUE TITLE
API til Dine Utbetalinger (Lånekassen)

### ISSUE THREAD

**Issue by SandraSolberg** [difi/dc20-digitalborger-frontend#145]
Lage API med dato, hendelse og sum for dine utbetalinger tab

**Comment by bjowei** [comment]
Ønska format:

const Betalinger = [
    {
        date: '16.04.2020',
        occurrence:'Utbetaling',
        sum: 11020,
    },
    {
        date: '15.03.2020',
        occurrence:'Utbetaling',
        sum: 8265,
    },
    {
        date: '14.02.2020',
        occurrence:'Utbetaling',
        sum: 8265,
    },
    {
        date: '14.01.2020',
        occurrence:'Utbetaling',
        sum: 8265,
    },
    {
        date: '14.12.2019',
        occurrence:'Utbetaling',
        sum: 8200,
    },
    ];

**Comment by bjowei** [comment]
Dette er no fiksa i commit 8fb4de64fa91996d396e7f39dfbafafd8caf7682
(link: http://git.difi.local/dc20-drupal8-profile-dib.git/commit/8fb4de64fa91996d396e7f39dfbafafd8caf7682)

Json respons ser no slik ut:

[
    {
        "date": "2020-06-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2020-05-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2020-04-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2020-03-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2020-02-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2020-01-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2019-12-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2019-11-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2019-10-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2019-09-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2019-08-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    },
    {
        "date": "2019-07-12",
        "occurence": "Utbetaling",
        "sum": "6035"
    }
]
