### ISSUE TITLE
Lånekassen - neste utbetaling

### ISSUE THREAD

**Issue by ingvildvarahagen** [difi/dc20-digitalborger-frontend#18]
Brukeren skal kunne se neste utbetaling/utbetalinger

**Comment by bjowei** [comment]
No kan ein sjå neste utbetaling til ein brukar i APIet ved å sende personnummer i URL slik:

http://feat01-drupal8.dmz.local/dib/laanekassen/23079418366

Dette kan evt bli gjort annarleis for å unngå personnummer i URL seinare.
