### ISSUE TITLE
Lånekassen - stipend/lån 

### ISSUE THREAD

**Issue by ingvildvarahagen** [difi/dc20-digitalborger-frontend#19]
Gi brukeren en videre link til søknad om stipend og lån

**Comment by bjowei** [comment]
No kan ein sjå lånet til ein brukar i APIet ved å sende personnummer i URL slik:

http://feat01-drupal8.dmz.local/dib/laanekassen/23079418366

Dette kan evt bli gjort annarleis for å unngå personnummer i URL seinare.
