### ISSUE TITLE
Link til oppretting av elektronisk ID

### ISSUE THREAD

**Issue by hegeaal** [difi/dc20-digitalborger-frontend#2]
Brukeren skal kunne bli sendt videre til side for oppretting av elektronisk ID

**Comment by jonmyk** [comment]
http://feat01-drupal8.dmz.local/dib/jsonapi/node/elektronisk_id

**Comment by jonmyk** [comment]
Inneheld ein lenke til oppretting av min id samt en lenke til side med informasjon vedrørande bank-id
