### ISSUE TITLE
Push notification nedtelling

### ISSUE THREAD

**Issue by ingvildvarahagen** [difi/dc20-digitalborger-frontend#9]
Brukeren skal få en push notification når nedtellingen for en viktig personlig dato har 24 timer igjen

**Comment by hegeaal** [comment]
Har laget push notifications som man kan få dersom appen er åpen og koden kjører, dvs. funger til fremvisning men ikke i praksis. Dersom man vil ha push varslinger mens appen er lukket må backend fikse dette (de skulle se på det).
